-- Databricks notebook source
DROP Table aa  ;
CREATE TABLE aa (chyear STRING, vinpattern STRING, numofstyles STRING, numoftrims STRING, numofmodels STRING, numofMKTCLASSID STRING, numofvehclass STRING, numofENGINESIZE STRING, numofTRANSMISSIONTYPE STRING, numofFUELTYPECATEGORYID STRING, numofENGINETYPE STRING, bvin STRING, bvinyr STRING, chmake STRING, chmodel STRING, VINMODELNAME STRING, chstyle STRING, chtrim STRING, CHROMESTYLEID STRING, SUBDIVISIONNAME STRING, COUNTRY STRING, FLEETONLY STRING, ENGINESIZE STRING, MANUALTRANSAVAIL STRING, AUTOTRANSAVAIL STRING, TRANSMISSIONTYPECATEGORYID STRING, FUELTYPECATEGORYID STRING, ENGINETYPECATEGORYID STRING, FORCEDINDUCTIONCATEGORYID STRING, MODELYEAR STRING, MODELID STRING, CFMODELNAME STRING, CFSTYLENAME STRING, CFDRIVETRAIN STRING, CFBODYTYPE STRING, PASSENGERDOORS STRING, PASSENGERCAPACITY STRING, MKTCLASSID STRING, STYLENAME STRING, TRIM STRING, INVOICE STRING, MSRP STRING, DESTINATION STRING, FOURWD STRING, FRONTWD STRING, ALLWD STRING, REARWD STRING, AUTOTRANS STRING, MANUALTRANS STRING, TRUEBASEPRICE STRING, AVAILABILITY STRING, MARKETCLASS STRING, FUELTYPE STRING, ENGINETYPE STRING, TRANSMISSIONTYPE STRING, FORCEDINDUCTION STRING, VFSUB2CLASS STRING, VFSUB1CLASS STRING, VFCLASS STRING, vehicleclass STRING) 


-- COMMAND ----------

show create table aa

-- COMMAND ----------

